# Generated by Django 4.0.6 on 2022-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyName', models.CharField(max_length=40)),
                ('Qilification', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=10)),
                ('Seminar', models.BooleanField(default=False, verbose_name='Seminar')),
                ('Workshop', models.BooleanField(default=False, verbose_name='Workshop')),
                ('Webinar', models.BooleanField(default=False, verbose_name='Webinar')),
                ('FDP', models.BooleanField(default=False, verbose_name='FDP')),
                ('Symposium', models.BooleanField(default=False, verbose_name='Symposium')),
                ('Others', models.BooleanField(default=False, verbose_name='Others')),
                ('GuestLecturer', models.BooleanField(default=False, verbose_name='Guest Lecturer')),
                ('AlumniLecturer', models.BooleanField(default=False, verbose_name='Alumni Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='uploo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fil', models.FileField(upload_to='')),
                ('Upload_Photo_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='worksphop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infor', models.CharField(max_length=2000)),
            ],
        ),
    ]
