# Generated by Django 4.0.6 on 2022-07-21 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_ddd_uploo_worksphop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddd',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
