# Generated by Django 4.0.6 on 2022-07-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_ddd_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddd',
            name='AlumniLecturer',
        ),
        migrations.RemoveField(
            model_name='ddd',
            name='FDP',
        ),
        migrations.RemoveField(
            model_name='ddd',
            name='GuestLecturer',
        ),
        migrations.RemoveField(
            model_name='ddd',
            name='Others',
        ),
        migrations.RemoveField(
            model_name='ddd',
            name='Seminar',
        ),
        migrations.RemoveField(
            model_name='ddd',
            name='Symposium',
        ),
        migrations.RemoveField(
            model_name='ddd',
            name='Webinar',
        ),
        migrations.RemoveField(
            model_name='ddd',
            name='Workshop',
        ),
        migrations.AddField(
            model_name='ddd',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ddd',
            name='parpose',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ddd',
            name='Date',
            field=models.CharField(max_length=12),
        ),
    ]
