# Generated by Django 4.0.6 on 2022-07-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_ddd_upload_photo_file_ddd_fil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploo',
        ),
    ]
