# Generated by Django 4.0.6 on 2022-07-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_delete_uploo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddd',
            old_name='Date',
            new_name='Datee',
        ),
    ]
