# Generated by Django 4.0.6 on 2022-07-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_date_ddd_datee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddd',
            name='Qilification',
        ),
    ]
