# Generated by Django 4.0.6 on 2022-07-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_ddd_qilification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddd',
            name='personone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ddd',
            name='persontree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ddd',
            name='persontwo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
