# Generated by Django 4.0.6 on 2022-07-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='papertitle',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='pub',
            name='yearofpub',
            field=models.CharField(max_length=100),
        ),
    ]
