# Generated by Django 4.0.6 on 2022-08-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookchappub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=254)),
                ('isbn', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=200)),
                ('certifi', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='bookpub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=40)),
                ('Author', models.CharField(max_length=254)),
                ('isbn', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('mandy', models.CharField(max_length=12)),
                ('bookwra', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='researarticcal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=254)),
                ('artical', models.CharField(max_length=100)),
                ('pageno', models.IntegerField()),
                ('certifi', models.FileField(upload_to='')),
            ],
        ),
    ]
