# Generated by Django 4.0.6 on 2022-08-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_bookchappub_bookpub_researarticcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchappub',
            name='mandy',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researarticcal',
            name='mandy',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pub',
            name='Sno',
            field=models.IntegerField(),
        ),
    ]
