# Generated by Django 4.0.6 on 2022-08-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_bookchappub_mandy_researarticcal_mandy_alter_pub_sno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='day',
            new_name='dayy',
        ),
    ]
