# Generated by Django 4.0.6 on 2022-08-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_conference_dayy'),
    ]

    operations = [
        migrations.AddField(
            model_name='researarticcal',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
