# Generated by Django 4.0.1 on 2022-08-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_researarticcal_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddd',
            name='Email',
        ),
    ]
