# Generated by Django 4.0.6 on 2022-08-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_remove_ddd_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('pno', models.IntegerField()),
                ('regno', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('dep', models.CharField(max_length=100)),
                ('compdet', models.CharField(max_length=500)),
                ('fullad', models.CharField(max_length=300)),
                ('datee', models.CharField(max_length=14)),
                ('fil', models.FileField(upload_to='')),
                ('Upload_Photo_file', models.FileField(upload_to='')),
                ('Attendance', models.FileField(upload_to='')),
            ],
        ),
    ]
