# Generated by Django 4.0.6 on 2022-08-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_placesel'),
    ]

    operations = [
        migrations.CreateModel(
            name='studet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('dep', models.CharField(max_length=100)),
                ('blood', models.CharField(max_length=30)),
                ('datee', models.CharField(max_length=14)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=500)),
            ],
        ),
    ]
