# Generated by Django 4.0.6 on 2022-08-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_studet_yearof'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpub',
            name='fill',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
